### ISSUE TITLE
An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/ v1.24/images/create?fromImage=uvms%2Fpostgres&tag=9.3

### ISSUE THREAD

**Issue by gkgeorgiev** [UnionVMS/UVMS-Docker#1]
So, I cloned the master, and I followed the steps described in the readme.md, but I get the following error during the build.bat step:

> 
> C:\dev\git\UVMS-Docker>docker pull uvms/postgres:9.3
> Warning: failed to get default registry endpoint from daemon (An error occurred
> trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: open //
> ./pipe/docker_engine: The system cannot find the file specified.). Using system
> default: https://index.docker.io/v1/
> An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/
> v1.24/images/create?fromImage=uvms%2Fpostgres&tag=9.3: open //./pipe/docker_engi
> ne: The system cannot find the file specified.

> 
> C:\dev\git\UVMS-Docker>docker pull uvms/wildfly:8.2.0
> Warning: failed to get default registry endpoint from daemon (An error occurred
> trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: open /
> ./pipe/docker_engine: The system cannot find the file specified.). Using system
> default: https://index.docker.io/v1/
> An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine
> v1.24/images/create?fromImage=uvms%2Fwildfly&tag=8.2.0: open //./pipe/docker_en
> ine: The system cannot find the file specified.
> 
> C:\dev\git\UVMS-Docker>docker build --tag uvms/postgres-full --no-cache postgre
> 
> An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine
> v1.24/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&c
> usetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&no
> ache=1&rm=1&shmsize=0&t=uvms%2Fpostgres-full&ulimits=null: open //./pipe/docker
> engine: The system cannot find the file specified.
> 
> C:\dev\git\UVMS-Docker>docker build --tag uvms/wildfly-full --no-cache wildfly
> An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine
> v1.24/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&c
> usetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&no
> ache=1&rm=1&shmsize=0&t=uvms%2Fwildfly-full&ulimits=null: open //./pipe/docker_
> ngine: The system cannot find the file specified.
>

**Comment by gkgeorgiev** [comment]
It seems that it's well known issue related to the initialization of Kitematic.
I get 
![image](https://cloud.githubusercontent.com/assets/7082716/19970071/2c636334-a1db-11e6-94a1-1356a4a7ce96.png)

**Comment by uvms** [comment]
@negod Says that you can just click Use virtualbox, if you are running Win 7.
IT also seems that the error can occur if you are using cmd or some other terminal than Docker Quickstart Terminal https://github.com/docker/toolbox/issues/528

**Comment by gkgeorgiev** [comment]
Yep, just tried and it seems working.
