### ISSUE TITLE
Wildfly 2.1.1 doesn't start

### ISSUE THREAD

**Issue by gkgeorgiev** [UnionVMS/UVMS-Docker#3]
The wildfly container doesn't start: 

/opt/jboss/wildfly/bin/standalone.sh: line 258:    70 Killed                  "/usr/lib/jvm/java/bin/java" -D"[Standalone]" -server -Xms2048m -Xmx2048m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n "-Dorg.jboss.boot.log.file=/opt/jboss/wildfly/standalone/log/server.log" "-Dlogging.configuration=file:/opt/jboss/wildfly/standalone/configuration/logging.properties" -jar "/opt/jboss/wildfly/jboss-modules.jar" -mp "/opt/jboss/wildfly/modules" org.jboss.as.standalone -Djboss.home.dir="/opt/jboss/wildfly" -Djboss.server.base.dir="/opt/jboss/wildfly/standalone" "-c" "standalone-uvms.xml" "-b" "0.0.0.0" "-bmanagement" "0.0.0.0" --debug 8787

**Comment by negod** [comment]
On win 7 you need to increase the memory on the virtualbox. I use about 3 - 4 Gb of ram. If you restart it will probably stop on another line. When memory runs out the wildfly server stops instant.

**Comment by gkgeorgiev** [comment]
Joa, the following line in the run.sh says 6G, right?

docker run -it -p 9990:9990 -p 8787:8787 -p 8080:8080 --name wildfly --net-alias wildfly --net=uvms -m 6G -d uvms/wildfly-release:2.1.1

**Comment by gkgeorgiev** [comment]
OK, it was indeed, the RAM of my VirtualBox.
