### ISSUE TITLE
Mounting shared folders command

### ISSUE THREAD

**Issue by jjgenio** [UnionVMS/UVMS-Docker#4]
Could you please share the exact docker command for sharing/mounting windows directory.

It's regarding the step: 

> Share your C-drive with Docker: https://docs.docker.com/docker-for-windows/#shared-drives (For volume mounting, access to log files)

**Comment by uvms** [comment]
There is no docker command for doing this as we know of, What is the problem of doing it as the link proposes?

**Comment by gkgeorgiev** [comment]
Couldn't this be put in the build.bat/sh as a part of the setup ?

**Comment by Ozsie** [comment]
As far as I can find, there is no Docker command to share drives with Docker.

**Comment by Ozsie** [comment]
Also, this seems to work badly, or differently, on windows 7.

**Comment by gkgeorgiev** [comment]
yeah ... bit annoying, but this is something we can't upgrade soon.

**Comment by gkgeorgiev** [comment]
This issue is reproducible only on Windows 7 based docker installation. The problem is that the sharing of folders needs to be configured on several levels: VirtualBox image, Docker.
