### ISSUE TITLE
unable to open web interface

### ISSUE THREAD

**Issue by sunshuvo** [UnionVMS/UVMS-Docker#545]
Hi team,

Recently I installed UnionVMS-docker using http://nexus.focus.fish/nexus/repository/releases/eu/europa/ec/fisheries/uvms/docker/docker-compose/3.44.2/docker-compose-3.44.2.yml.

After docker-compose it showing running but unable to open the web interface. it installed on my centos.

Could you help me out?

Thank you

**Comment by ebrygg** [comment]
Hi!
docker-compose -f docker-compose-3.44.2.yml up -d 
The web interface can be reached at http://localhost:28080
Use vms_admin_se/password to logon and poke around.

I would recommend the release below to get some data into the system (fair warning, it will consume a lot of resources starting up):
http://nexus.focus.fish/nexus/repository/releases/eu/europa/ec/fisheries/uvms/docker/docker-compose/3.44.2/docker-compose-3.44.2-ais.yml

**Comment by sunshuvo** [comment]
> Hi!
> docker-compose -f docker-compose-3.44.2.yml up -d
> The web interface can be reached at http://localhost:28080
> Use vms_admin_se/password to logon and poke around.
> 
> I would recommend the release below to get some data into the system (fair warning, it will consume a lot of resources starting up):
> http://nexus.focus.fish/nexus/repository/releases/eu/europa/ec/fisheries/uvms/docker/docker-compose/3.44.2/docker-compose-3.44.2-ais.yml

Thanks for your reply. 
I already complete this. The problem was physical memory not as required, so the wildfly unable to start properly and after a while it automatically shutdown. 

I have another question: The VMS is basically based on satellite communication for Mobile Terminal, is there any way to communicate using IP.

**Comment by ebrygg** [comment]
The https://github.com/UnionVMS/UVMS-AIS-PLUGIN does something along what you are asking for in combination with the https://github.com/UnionVMS/UVMS-AIS-RESOURCE-ADAPTER

**Comment by sunshuvo** [comment]
> The https://github.com/UnionVMS/UVMS-AIS-PLUGIN does something along what you are asking for in combination with the https://github.com/UnionVMS/UVMS-AIS-RESOURCE-ADAPTER
Thank you for your reply. 
How can I use it on docket Uvms. Is there any documentation for it?

**Comment by ebrygg** [comment]
This release http://nexus.focus.fish/nexus/repository/releases/eu/europa/ec/fisheries/uvms/docker/docker-compose/3.44.2/docker-compose-3.44.2-ais.yml
uses the ais plugin and provides data through a simulator. The current documentation is mainly through the tests provided, both the integrations tests in the docker project and in the individual artifacts.

**Comment by sunshuvo** [comment]
Thank you Ebrygg. I will try

**Comment by ebrygg** [comment]
Ok, so I'm closing this issue
