### ISSUE TITLE
404 - Not Found after running docker-compose

### ISSUE THREAD

**Issue by kplaczek** [UnionVMS/UVMS-Docker#70]
I followed instructions provided on this page: https://focusfish.atlassian.net/wiki/spaces/UVMS/pages/11403266/Docker+Installation and after `docker-compose up `-d` command doing it's thing all I can see on localhost:28080/unionvms is 404 page. Wildfly, postgres and activemq containers are up and running. When I try access localhost:28080 all i see is default WildFly 8 page. Am I missing something?

**Comment by MathiasBulte** [comment]
Check the Wildfly admin console on localhost:29990 (admin/admin). If it says "server is still booting", wait a few more minutes and it should work.

**Comment by kplaczek** [comment]
Thanks for the reply. This was the case. I had to wait for really long time for the app to boot up. So in case if all the containers are up and logs contains no errors just wait 15 more minutes.
